// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecretSanta;

namespace SecretSanta.Migrations
{
    [DbContext(typeof(SecretSantaContext))]
    [Migration("20201210211120_inital_create")]
    partial class inital_create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("SecretSanta.SecretSantaParticipant", b =>
                {
                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GiftIdeas")
                        .HasColumnType("text");

                    b.Property<string>("GiverForeignKey")
                        .HasColumnType("text");

                    b.Property<bool>("HasGiver")
                        .HasColumnType("boolean");

                    b.Property<string>("MatchForeignKey")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("PhoneNumber");

                    b.HasIndex("GiverForeignKey");

                    b.HasIndex("MatchForeignKey");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("SecretSanta.SecretSantaParticipant", b =>
                {
                    b.HasOne("SecretSanta.SecretSantaParticipant", "Giver")
                        .WithMany()
                        .HasForeignKey("GiverForeignKey");

                    b.HasOne("SecretSanta.SecretSantaParticipant", "Match")
                        .WithMany()
                        .HasForeignKey("MatchForeignKey");

                    b.Navigation("Giver");

                    b.Navigation("Match");
                });
#pragma warning restore 612, 618
        }
    }
}
